language: python
python:
    - 2.7

install: 
    - sudo apt-get install libmysqlclient-dev
    - pip install -r requirements.txt

script: 
    - nosetests --verbose --with-coverage --cover-package=propertysuggester --cover-min-percentage=80

after_success:
    - coveralls debug
    - coveralls
